github/opensource.guide

_articles/starting-a-project.md
I assume this is what the author intended.
=> Fix typo: . → ,

_articles/legal.md
=> fixed typo

js/search_worker.js
```diff
- Initalize
+ Initialize
```
=> Fix typo Initalize -> Initialize

_articles/getting-paid.md
Hi y'all!
Thank you so much for creating these guides. They're amazing and I love them. ❤️
I noticed a typo, so I figured I would try to contribute! I did my best to make sure nobody else was working on this yet, but if I missed anything, please let other go first!
I changed "an contributor" to "a contributor".
Let me know if all is okay, or if I should change something. Have a great day!
=> Fix typo in getting-paid.md

_layouts/article-alt.html, _layouts/article.html, index.html
=> Fix spacing bug in navbar items

_articles/how-to-contribute.md
I think there are more structural changes that may be necessary; specifically, the code/non-code division reinforces the very thing it's trying to address. But ... that requires more thought, so here's a quick fix.
=> Work UI and UX design into how to contribute

_articles/how-to-contribute.md
I have nothing against discussing burritos at night but I believe it’s a typo. Feel free to close if I’m wrong ;-)
=> Fix possible typo

js/script.js
=> Fix issue-239

_layouts/article-alt.html, _layouts/article.html
Discussed in #287
Also fixes #227
=> Remove the trailing slash in breadcrumbs

_articles/leadership-and-governance.md
It's one of the largest sponsors of open source projects:
https://www.linuxfoundation.org/projects
=> Add Linux Foundation

_articles/how-to-contribute.md
=> Add contributor-ninja to discover new projects

_articles/getting-paid.md
more based on Ashe Dryden's blog, since this isn't really described at all now in the document - there's just a link to this blog post sitting out by itself, waiting for someone to be curious and click on it
=> commenting more on diversity and ethics

_articles/best-practices.md
* point to our blog and our video on protected branches as a technical mechanism that can be used to enforce all tests running through
=> Protected branches to require tests passing

_articles/metrics.md
=> adding grants as a motivation for metrics

docs/roadmap.md
This just bumps the timing up from first and second half of 2017 to first and second quarter.
Once the dust settles a little more from the launch we'll solicit feedback and put together a more detailed roadmap.
=> Update timing of roadmap

_includes/footer.html
I think the blue with underline is a bit glaring for the link ... but I'm not familiar enough with Primer to fix it. @bkeepers can you lend a ✋ ? Or do you think it is ok as is?
=> Add link to contributors graph from "and you" in footer

CONTRIBUTING.md
Upon clicking the anchor link, the user will be directed to the appropriate section.
=> Fix anchor link to Style guide section

_articles/legal.md
Haven't been able to test locally yet because nokogiri :cry:
Fixes #332
=> Fix broken links

CONTRIBUTING.md
Clarify the policy on linking _or referencing_ your own work.
=> Links or references to your own work

_articles/legal.md
=> Note explicit inbound=outbound in new GitHub ToS

notices.md
=> copyright (c) Open Source Guides authors

js/script.js
🔥  commented JS code.
@sophshep
=> remove commented code

_layouts/default.html
demo: https://open-craft-guild.github.io/open-source-guide/#mc_embed_signup
/cc: @bkeepers
=> Enable localised jquery-validation error strings

CONTRIBUTING.md, docs/new-guides.md
A few people have proposed new guides. @bkeepers and I briefly discussed coming up with a process to manage these.
If this looks good I'll rework the existing ```new-guide``` issues so they match this format.
cc @kytrinyx @hzoo @thejameskyle @lee-dohm @shazow @TheLarkinn who have discussed new guides
cc @sophshep @jeejkang @brennaheaps for the design part of it
=> Proposed process for writing new guides

_articles/finding-users.md
I looked around to see if "deeper diver" might be an expression but I couldn't find it used outside of a PADI context!
=> Fix typo (diver -> dive)

google19d329aaa468a71f.html
Will help us view search metrics :-)
And optimize for SEO. 🤘
=> Added Google Search Verification file

assets/css/custom.scss
=> Add transition to button

_articles/how-to-contribute.md
Incorrect use of "awhile" on line 466. Should be "a while".
http://grammarist.com/spelling/awhile-a-while/
=> Fix grammar

_includes/footer.html
The previous one was pretty terrible so this will be at least consistent.
=> footer: update email list copy.

_articles/code-of-conduct.md
=> Better link instructions for CODE_OF_CONDUCT #399

_articles/building-community.md
It’s useful for people to have a data-based justification for why documentation is so important for projects.
=> building-community: link to Open Source Survey.

search.html
Closes #391. We don't have search yet, so removing this page for SEO purposes.
=> Remove blank search page

_articles/starting-a-project.md
Broken link from #376 is fixed, so we're doing the Steely Dan thing and going back.
=> Bring back ivantomic link

.travis.yml
Same as done at https://github.com/github/choosealicense.com/pull/540
-----
=> libcurl4-openssl-dev to avoid SSL errors in tests

docs/templates/translation-issue-template.md
=> fix typo in repository,preview link

_data/locale/en-US.yml, index.html
-----
I'm working in pt-BR translation (https://rogeriopradoj.github.io/opensource.guide/) and something surprised me: in home page a big notice in English about opensourcefriday.org. With this PR, translators could localize the notice.
=> i18n Open Source Friday index lead

CONTRIBUTING.md
-----
Adding `it` to fix the sentence: `When adding content, please consider if it is widely valuable.`
=> Type fix - Adding a missing word

_articles/en-US/best-practices.md
Added a paragraph under `Documenting your processes` talking about the obsolescence of documentation, according to issue #468.
-----
=> Adding information about outdated information

_articles/en-US/legal.md
So as not to overload "copy", which one can do (but only via the "fork" mechanism), and copying can mean different things to different people, including making derivative works.
Fixes #495
=> Copy->distribute

_articles/id/best-practices.md, _articles/id/building-community.md, _articles/id/code-of-conduct.md, _articles/id/finding-users.md, _articles/id/getting-paid.md, _articles/id/how-to-contribute.md, _articles/id/leadership-and-governance.md, _articles/id/legal.md, _articles/id/metrics.md, _articles/id/starting-a-project.md, _data/locales/id.yml, id.html
=> Id: Added Indonesian Translations

_data/locales/id.yml
Signed-off-by: Willy Sudiarto Raharjo <willysr@gmail.com>
-----
=> ID: Fix locale_name.

_layouts/article-alt.html, assets/css/covers.scss
=> Fix article-alt header

assets/js/locale.js
Correctly handle switching from non-English to another non-English page.
=> js/locale: fix language switcher.

_data/locales/en.yml
-----
Sorry, this is my mistake.
=> [Update en.yml] Revert en name

_articles/ko/how-to-contribute.md, _articles/ko/legal.md, _articles/ko/starting-a-project.md, _data/locales/ko.yml
-----
I saw this issue and commit it.
#553
=> Translate untranslated ko text.

LICENSE, _articles/best-practices.md, _articles/es/best-practices.md, _articles/id/best-practices.md, _articles/ko/best-practices.md, _articles/ko/getting-paid.md, _articles/ko/leadership-and-governance.md
Stick to the nice ASCII ones (which Jekyll will convert for us anyway).
=> Don’t use curly quotes.

README.md, _articles/zh-cn/building-community.md, _articles/zh-cn/legal.md, _config.yml, _includes/nav.html
This should be more obvious to people unfamiliar with GitHub Pages.
=> Change default branch to master

docs/translations.md, script/test
This has been missed by a few people so make sure they get it here rather than being surprised by broken CI.
Also, ensure that both HTML Proofer and Prose checks are run every time even if HTML Proofer fails to produce better CI output.
=> docs/translations: note testing step.

_config.yml
Remove some defaults and cleanup existing values.
=> _config.yml: general cleanup.

_config.yml
Used by the Jekyll SEO plugin.
=> config: add logo.

script/html-proofer
=> html-proofer: enable more (passing) checks.

_articles/es/how-to-contribute.md
There is a typo in the spanish contributing guide
This is my 1st commitment so please be patient 🇦🇷 😃
=> Typo fixed

_articles/finding-users.md
This PR attempts to improve the clarity of finding-users.md by re-structuring sentences and replacing pronouns, such as "it" and "they", with proper nouns.
=> Improve finding-users.md's clarity

_articles/metrics.md
-----
The term seems to have been updated in GitHub's GUI: https://help.github.com/articles/viewing-traffic-to-a-repository/
=> Reflect renaming: Graph -> Insights

_articles/es/leadership-and-governance.md, _articles/id/leadership-and-governance.md, _articles/ko/leadership-and-governance.md, _articles/leadership-and-governance.md, _articles/zh-cn/leadership-and-governance.md
=> Fix PyPI link

_articles/es/legal.md, _articles/id/legal.md, _articles/ko/legal.md, _articles/legal.md, _articles/zh-cn/legal.md
-----
An external resource was moved, see diff & https://travis-ci.org/github/opensource.guide/builds/375057138#L1325
=> Update hyperlink to avoid html-proofer error

_articles/es/code-of-conduct.md, _articles/es/starting-a-project.md, _articles/id/code-of-conduct.md, _articles/ko/code-of-conduct.md, _articles/ko/starting-a-project.md, _articles/starting-a-project.md, _articles/zh-cn/code-of-conduct.md, _articles/zh-cn/starting-a-project.md
=> update contributor covenant site URL to avoid 301

docs/translations.md
Based on example provided by @katrinleinweber at https://github.com/github/opensource.guide/pull/577#issuecomment-395047670
-----
=> Document translation fork collaboration

_articles/best-practices.md, _articles/es/best-practices.md, _articles/fr/best-practices.md, _articles/id/best-practices.md, _articles/ko/best-practices.md, _articles/zh-cn/best-practices.md
-----
Hello! The `?files=1` causes description & topics to be hidden. Since the quote below doesn't address the files specifically, I suggest to not focus the link on those.
=> Ensure users see P5.js description & topics

_articles/es/legal.md, _articles/fr/legal.md, _articles/id/legal.md, _articles/ko/legal.md, _articles/legal.md, _articles/zh-cn/legal.md
=> Update link to fix 404

.bowerrc
Bower was removed in https://github.com/github/opensource.guide/pull/356
-----
=> Remove .bowerrc missed in bower removal

_articles/es/index.html, _articles/fr/index.html, _articles/id/index.html, _articles/ko/index.html, _articles/ta/index.html, _articles/zh-cn/index.html, _layouts/index.html
-----
I moved index files for each language into their own directories. This keeps simpler root directory even while we're putting more and more languages.
=> Move index files into their own language directories

_articles/zh-cn/finding-users.md
- [√ ] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/master/CONTRIBUTING.md)?
- [ √] Have you explained what your changes do, and why they add value to the Guides?
fix several typo and  use native expression
-----
ZH_CN：修改了数个输入和拼写错误，增加了少数几个惯用表达和稍书面化的表达。
@lijiangsheng1 Cloud u pls help to review ? Thx.
=> fix several typos and  use native expression

_articles/building-community.md, _articles/es/building-community.md, _articles/fr/building-community.md, _articles/id/building-community.md, _articles/ko/building-community.md, _articles/ta/building-community.md, _articles/zh-cn/building-community.md, script/html-proofer
Others tend to be random SSL blips or Travis CI issues.
-----
=> html-proofer: only report 4xx errors.

_articles/ko/legal.md
- [v] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/master/CONTRIBUTING.md)?
- [v] Have you explained what your changes do, and why they add value to the Guides?
-----
typo fix in korea
=> docs: change korean awkward representation legam.md

_articles/how-to-contribute.md
This PR is made following this issue #739 
Fixes #739 
-----
=> Add first contributions

_articles/de/how-to-contribute.md, _articles/es/how-to-contribute.md, _articles/fr/how-to-contribute.md, _articles/how-to-contribute.md, _articles/id/how-to-contribute.md, _articles/ko/how-to-contribute.md, _articles/ta/how-to-contribute.md, _articles/zh-cn/how-to-contribute.md
The idea is very good, and I like it that it is on twitter. But seems like it hasn't been updated since last year.
- [x ] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/master/CONTRIBUTING.md)?
- [ x] Have you explained what your changes do, and why they add value to the Guides?
=> Remove yourfirstpr

_articles/zh-cn/getting-paid.md
=> wrong word use [zh]

_layouts/article.html, docs/translations.md
- `layouts/article`: fix ToC language variable. Otherwise this isn't shown for English either.
- `docs/translations`: note ToC changes.
=> Translation ToC tweaks

_articles/de/starting-a-project.md, _articles/es/starting-a-project.md, _articles/fr/starting-a-project.md, _articles/id/starting-a-project.md, _articles/ko/starting-a-project.md, _articles/starting-a-project.md, _articles/ta/starting-a-project.md, _articles/zh-cn/starting-a-project.md, _includes/head.html
Move this blog post to the new destination.
=> Fix broken link

_includes/footer.html, _includes/nav.html, assets/css/custom.scss
This matches Open Source Friday and make it more accessible.
Fixes #822
=> Move language selection to header.

_articles/es/starting-a-project.md
I used the "male" form of the project (UIAlertView) changing the `lo` to `la`, and the `I`(in English)  is a `Y` in spanish.. (by the way I'm a native Spanish speaker).
-----
=> Minor Fixes in the Translation

_articles/starting-a-project.md, notices.md
- [~] Have you enabled GitHub Pages Previews by pressing <keyboard>`Enable GitHub Pages`</keyboard> on the right sidebar to trigger a pages build for this PR?
-----
Since @18F's repos was archived, the page is no longer generated. Is that a reason to update to another page all together, or should we merely update the link to https://github.com/18F/open-source-guide/blob/18f-pages/pages/making-readmes-readable.md ?
Regarding <keyboard>`Enable GitHub Pages`</keyboard>: I'm not seeing such a checkbox now and didn't see it when drafting the PR.
=> Swap @18F's archived README guide for @dguo's

_articles/de/starting-a-project.md
- [~] Have you enabled GitHub Pages Previews by pressing <keyboard>`Enable GitHub Pages`</keyboard> on the right sidebar to trigger a pages build for this PR?
-----
Follow-up to #913
=> Update German translation

.github/main.workflow, .github/test_runner/Dockerfile, .github/test_runner/entrypoint.sh
=> Implement GitHub Actions for testing

_articles/zh-cn/how-to-contribute.md
-----
Fix missing spacing between an adjacent Han character and a Western character.
Only spaces are added or removed. No actual content was changed. 
According to W3C's Requirements for Chinese Text Layout and for aesthetic reason, it is recommended that there is tracking or spacing between an adjacent Han character and a Western character of up to one quarter of a Han character width, except at the line start or end.
In addition, there is an inconsistency inside this doc regard to this principle. I think it should be handled properly.
[Requirements for Chinese Text Layout](https://www.w3.org/TR/clreq/)
Specifically: 
[3.2.2 Mixed Text Composition in Horizontal Writing Mode](https://www.w3.org/TR/clreq/#mixed_text_composition_in_horizontal_writing_mode)
=> Fix missing spacing in Chinese translation

_articles/id/starting-a-project.md
-----
Fix some typos in Indonesian translate
=> fix some typos

_articles/finding-users.md
- [ * ] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/master/CONTRIBUTING.md)?
- [ * ] Have you explained what your changes do, and why they add value to the Guides?
-----
Fixed editorial inconsistencies or inaccuracies
I corrected some of the grammatical errors found.
=> Fix editorial inconsistencies or inaccuracies

assets/js/locale.js
-----
Deploy in a sub dir. Its related to #828
=> Deploy in a sub dir

_articles/getting-paid.md, _articles/pt/getting-paid.md
=> Fix moved but not cool enough to be redirected link

_articles/pt/leadership-and-governance.md
Small text corrections in the Portuguese Translation 
--
Pequenas correções de texto na tradução para Português.
-----
=> Update leadership-and-governance.md Portuguese Translation

_articles/es/how-to-contribute.md
-----
This is my first contribution :) 
I was reading the article and i found a text saying "no dejes que de desanime" instead "no dejes que te desanime"
=> Fix finger mistake exists d instead t on "no dejes que de desanime"

_articles/how-to-contribute.md
-----
This change adds the SourceSort page (https://www.sourcesort.com) to the list of URLs on the Open Source Guide's list of places to find a project to contribute to (https://opensource.guide/how-to-contribute/#finding-a-project-to-contribute-to), therefore widening the potential list of places where developers can find open source projects.
=> added SourceSort to how-to-contribute article

_articles/zh-cn/how-to-contribute.md, _articles/zh-tw/how-to-contribute.md
-----
Fix editorial inconsistencies or inaccuracies
=> fix RP -> PR

_articles/how-to-contribute.md
-----
It feels to me like this is probably the single most important reason why people contribute to open source. Maybe I'm wrong about the priority order, but it would be weird if this reason was not mentioned at all.
Obviously, I'm open to moving the sub-section down (for now I added it on top of the list), and to rephrasing it entirely.
=> Mention "improve software you rely" as a reason to contribute.

docs/content-model.md, docs/personas.md, docs/styleguide.md, docs/translations.md
- add updating translations section cc @katrinleinweber 
- add lists guidance to content model
- make docs own style a bit more consistent
Started off wanting to memorialize my understanding of how we use lists to enhance narrative but avoid maintaining exhaustive, canonical, main feature, or bare lists. This has come up a few times as it's natural to want to add list items and I hate just saying no to well intentioned contributions.
Happy to be wrong on lists or other bits, please review or comment if you think so.
=> Update docs for this project

_articles/legal.md
-----
There was a grammatical error that was fixed in the legal section.
=> fixed grammar error.

_articles/pt/getting-paid.md
Corrected the writing of the word 'projeto'
-----
=> Typo fix in getting-paid article

_articles/starting-a-project.md
=> Fixed typo in starting-a-project.md

README.md
Followup to #1251 based on skim of https://help.github.com/en/actions/automating-your-workflow-with-github-actions/configuring-a-workflow#adding-a-workflow-status-badge-to-your-repository
=> Attempt to replace Travis badge with Actions badge

_data/locales/hu.yml
=> fix: hu translation on hu.yml

Gemfile.lock
avoid failure or needing to install bunlder1
=> CI now running ruby 2.7.0 so update to bunlder2

.github/workflows/tests.yml
eg https://github.com/github/opensource.guide/runs/408831573#step:4:216
=> See if setting up node fixes CI bootsrap error

_articles/ro/building-community.md
replicate d394ee0a0d7dac492436c077cb4de3a35054b803 for ro translation
=> Update quoted user link

.github/workflows/tests.yml
-----
Hi team 👋 , I'm opening this PR to cache bundler dependencies at CI build. This change is going to speed up the build from 4 minutes to 1.5 minutes (see [here](https://github.com/yuichielectric/opensource.guide/runs/435427570?check_suite_focus=true)).
[actions/cache bundler example](https://github.com/actions/cache/blob/master/examples.md#ruby---bundler)
=> Cache bundler dependencies

_articles/de/how-to-contribute.md, _articles/es/how-to-contribute.md, _articles/fr/how-to-contribute.md, _articles/how-to-contribute.md, _articles/hu/how-to-contribute.md, _articles/id/how-to-contribute.md, _articles/ja/how-to-contribute.md, _articles/ko/how-to-contribute.md, _articles/pt/how-to-contribute.md, _articles/ro/how-to-contribute.md, _articles/ta/how-to-contribute.md, _articles/tr/how-to-contribute.md, _articles/zh-hans/how-to-contribute.md, _articles/zh-hant/how-to-contribute.md
=> Update realm.io link that doesn't redirect to new link

docs/translations.md
=> Translators need to set up their environment, can send in progress PR

docs/translations.md, script/html-proofer
Add note about fork repo collaborators to translation doc, hopefully encouraging more collaborative and less stalled translations.
=> Add note about fork repo collaborators to translation doc

_articles/tr/how-to-contribute.md, _articles/tr/starting-a-project.md, _data/locales/tr.yml
=> Fix Some Typos On Turkish Translation

_articles/zh-hans/getting-paid.md
* make the language is more Comfortable in Chinese 
* delete some redundant words
-----
=> make the language is more Comfortable in Chinese

_articles/pt/how-to-contribute.md
-----
While i was reading the article on How to Contribute to Open Source on the Portuguese Translation i found some typos and grammatical errors.
This PR fixes the ones i noticed.
=> Fix typos and grammatical errors

_articles/es/how-to-contribute.md
Added some missing periods, and corrected some spelling and writing errors on the spanish translation.
-----
=> Little corrections

_articles/tr/best-practices.md, _articles/tr/getting-paid.md, _articles/tr/legal.md, _articles/tr/starting-a-project.md
-----
Some contents in `aside` tags are not rendered correctly on Turkish translation. It seems the cause is the incorrect indentation.
With this PR, this bug is fixed.
=> Fix Rendering Problem On Turkish

_articles/pt/starting-a-project.md
=> accent correction in Portuguese

_articles/de/how-to-contribute.md, _articles/es/how-to-contribute.md, _articles/fr/how-to-contribute.md, _articles/hu/how-to-contribute.md, _articles/id/how-to-contribute.md, _articles/ja/how-to-contribute.md, _articles/ko/how-to-contribute.md, _articles/pt/how-to-contribute.md, _articles/ta/how-to-contribute.md, _articles/zh-hans/how-to-contribute.md, _articles/zh-hant/how-to-contribute.md
-----
This PR adds the [Poppins](https://github.com/bancodobrasil/poppins) project to the list of resources for first-timers.
Poppins is a manifesto that states the importance of having entire open source projects focused on beginners and first contributors and how to do guides. A project is considerate a "Poppins project" if it is mainly managed to help beginners to level up their skills and increase their experience with OSS in a mentorship community atmosphere.
-----
As a corollary of this PR, I noticed some translation inconsistencies with the list of resources for first-timers. This PR also fixes that.
=> adds poppins and reviews lists of first-timers resources

_articles/tr/index.html, _data/locales/tr.yml
-----
Here are some improvements of Turkish translation page:
* ucfirst for `title` variable
* instead of "ile beraber", "by"->"tarafından"
=> Turkish translation improvements

_articles/es/legal.md, _data/locales/es.yml
-----
Fixing some Spanish translations errors, so my contribution is minor.
=> es: Typo Fix Minor Spanish

_articles/ja/index.html
-----
missing Japanese title in index page.
I add title in Japanese page.
=> add index title in japanese page.

_articles/pt/how-to-contribute.md
-----
Just a little modification in translation for portuguese to get that more friendly. It isn't a spell check, but a more cultural adjustment since we are not in the habit of saying "leave something in a better place than when you found it", but "leave something better than when you found it"
=> Update translation for portuguese

_articles/pt/starting-a-project.md
Change "espectativas" to "expectativas".
- [x ] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/HEAD/CONTRIBUTING.md)?
- [x ] Have you explained what your changes do, and why they add value to the Guides?
-----
=> Fix pt translation grammar error

_articles/pt/starting-a-project.md
Acredito em ter arrumado o erro de digitação.
-----
=> correção de erro de digitação

_articles/getting-paid.md, _articles/hu/getting-paid.md, _articles/ja/getting-paid.md, _articles/ms/getting-paid.md, _articles/nl/getting-paid.md, _articles/pl/getting-paid.md, _articles/pt/getting-paid.md, _articles/tr/getting-paid.md
Changed `javascript` to `JavaScript`.
-----
=> Fix case of JavaScript.

CONTRIBUTING.md
=> Cosmetic change s/Guides/guides/

_articles/pl/index.html, _articles/pl/starting-a-project.md, _data/locales/pl.yml
-----
1) The main title has been translated - in addition, they will make it easier to search in search engines (SEO), if someone enters this phrase in Polish.
2) Forgot to translate the title of one chapter - I did it now :)
3) The word "friends" was translated in the footer
4)  in nav given the mother tongue "Polski" (in Poland "Polish" is "Polski", that is, in Polish) [I deposited the same in PR #1910 (my duplicate)]
=> [translation] missing titles translated for PL

_articles/pl/starting-a-project.md
-----
I translated the starting-a-project checklist into Polish
=> [translation] translated checklist in sections for PL

_articles/pl/metrics.md, _data/locales/pl.yml
-----
1) "am" remained, which meant that the exact question was not in Polish
2) in nav given the mother tongue "Polski" (in Poland "Polish" is "Polski", that is, in Polish)
=> corrections for PL

_articles/pl/how-to-contribute.md
-----
Added checklist translation in "how to contribute"
=> [translation] Translate checklist in how to contribute for PL

_articles/pt/how-to-contribute.md
-----
Minor adjustment in the **how to contribute** article portuguese translation on the [Open Source Guide](https://opensource.guide/pt/how-to-contribute/).
To provide a more appropriate translation for the phrase _"You did it!"_, with a more semantic and more used alternative for this ocasion.
Updated the `how-to-contribute.md` file.
Fixes #2023
=> Minor adjustment in how to contribute article portuguese translation

assets/js/ga.js, assets/js/index.js
Closes https://github.com/github/communities/issues/307
Part of 🍪 removal efforts!
=> Remove Google Analytics

_articles/zh-hant/building-community.md
Minor change, fix type 好的說明文建會 => 好的說明文件會
-----
=> Update building-community.md in zh_tw

_articles/es/how-to-contribute.md
-----
I found some typos in how-to-contribute  Spanish translation.
This PR fixes them.
=> Fix some typos in Spanish translation

_articles/fr/best-practices.md, _articles/fr/code-of-conduct.md, _articles/fr/finding-users.md, _articles/fr/getting-paid.md, _articles/fr/how-to-contribute.md, _articles/fr/leadership-and-governance.md, _articles/fr/legal.md, _articles/fr/metrics.md, _articles/fr/starting-a-project.md, _data/locales/fr.yml
-----
Fix some wording for titles and descriptions in french locale.
=> Update french titles and descriptions

_articles/hu/starting-a-project.md
-----
The WordPress link was bad.
```diff
- [WordPress] (https://github.com/WordPress)
+ [WordPress](https://github.com/WordPress)
```
=> Fixed the WordPress link

_articles/zh-hans/starting-a-project.md
Modify 2 incorrect words' translation, function and variable always stand for 函数 and 变量
-----
=> Modify 2 incorrect words

_articles/es/legal.md
=> Spanish translation

_articles/fr/legal.md, _articles/fr/starting-a-project.md
-----
Corrections d'ordre grammatical , ainsi que les tournures de phrases employées .
=> Fix editorial inconsistencies or inaccuracies starting-a-project.md

CODE_OF_CONDUCT.md, CONTRIBUTING.md, _articles/best-practices.md, _articles/building-community.md, _articles/getting-paid.md, _articles/how-to-contribute.md, docs/content-model.md, docs/personas.md, docs/styleguide.md, docs/translations.md
Improved and removed inaccuracies and inconsistencies from several markdown files.
-----
=> Fixing editorial inconsistencies

_articles/zh-hans/building-community.md, _articles/zh-hans/how-to-contribute.md, _articles/zh-hans/starting-a-project.md
=> make translation more native

_articles/pl/building-community.md
-----
I improved translate and grammar. Translate on polish is some weired...
=> Improved translate and grammar

_articles/es/how-to-contribute.md
In the section "Opening a pull request" one of the steps to open a pull request says "¡Has pruebas de tus cambios!". The word "Has" should be "Haz" (correct form of the imperative of the verb "hacer").
-----
=> Grammatic correction in the spanish translation

_articles/pt/how-to-contribute.md
-----
This is a simple change, using the **main** name instead of the  <strike>master</strike>
=> chore: :pencil: change branch name from master to main

_articles/metrics.md
* Add a chapter providing useful pointers for those who want to dive deeper into the metrics subject.
* Link to the CHAOSS community, as it is very relevant for open source metrics around open source development: It is a welcoming community with wide and varied participation. They discuss and develop metrics for open source development and develop open source tools to manage them. It's just the right place to go for help or knowledge.
I fear I might be violating the CONTRIBUTING.md where it says _"Please don't add references or links to things you or your employer have created"_ because I currently work for a company that joined that community and contributed some of their tools. But I really think this is **very relevant and valuable information for the readers** and I'm pointing to the …
=> Add "More..." chapter

_articles/pt/starting-a-project.md
I saw small typos in documentation.
- First: Article [Por que as pessoas tornam seu trabalho open source?](https://opensource.guide/pt/starting-a-project/#por-que-as-pessoas-tornam-seu-trabalho-open-source)
- From: ` **Transparência:** Qualquer um pode inspecionar um projeto open source por erros ou inconsistências. A transparência importa a governos como a [Bulgaria](https://medium.com/@bozhobg/bulgaria-got-a-law-requiring-open-source-98bf626cf70a) ou os [Estados Unidos](https://sourcecode.cio.gov/), industrias regulamentadas como bancos ou industrias de saúde, e softwares de segurança como [Let's Encrypt](https://github.com/letsencrypt).`
- To: ` **Transparência:** Qualquer um pode inspecionar um projeto open source por erros ou inconsistências. A transparência importa a governos como a …
=> solving start-a-project.md pt typo

_includes/footer.html
This reduces the amount of spam we see, based on other sites.
=> includes/footer: make contribute button link to blob not edit.

_articles/es/finding-users.md
Fixed a typo in description. "ponióndolo" should be "poniéndolo".
=> Typo fixed in description

_articles/pl/how-to-contribute.md
The Polish version of `How to contribute` had some literal translations from English, which made the sentences sound unnatural and sometimes they even did not make any sense. I made changes to idiom translations and I fixed grammar in some of the sentences, so that the article sounds more natural. 
-----
=> update how-to-contribute polish version

_articles/pl/how-to-contribute.md
I realized that there are sometimes possessive pronouns which start from uppercase and sometimes from lowercase in this article. In Polish they should be started uppercase only in emails and letters, so I unified them to be all lowercase.
-----
=> Fix uppercase possessive pronouns

_articles/pl/getting-paid.md
In this article there are also some literal translations from English into Polish. I fixed the translations of idioms, and added some grammar fixes to make it sound more natural in Polish.
-----
=> Update getting-paid polish version

_articles/pl/finding-users.md
This PR contains a set of grammar fixes and wording changes to make `finding-users` article in Polish sound more natural
-----
=> update finding-users polish article

_articles/de/building-community.md
-----
As in #2899, this PR adapts some phrases to German gender-sensitive language in the guide `Building Welcoming Communities`. (See `_articles/de/building-community.md`)
=> Fix gender-sensitive phrases

_articles/zh-hans/starting-a-project.md
An English comma was used here, which should be a Chinese one.
-----
=> chore: fixed wrong comma in Chinese

_articles/es/best-practices.md
=> Fixing commas and spanish expresions.

_includes/head.html
-----
This is simple favicon improvement. Provide icon based on system theme, just using `media` attribute.
**Before:**
**After:**
=> Add adaptive favicon

_data/locales/de.yml
- [ x ] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/HEAD/CONTRIBUTING.md)?
- [ x ] Have you explained what your changes do, and why they add value to the Guides?
Fixes the sentence which would otherwise end with ".:".
=> Remove redundant period

_articles/zh-hans/building-community.md
Sure
Some wording are not proper and Django part was missing. So I help to fix them.
-----
=> Polish and fix translation of simple Chinese

_articles/ko/how-to-contribute.md
-----
I found that some sentences in  translation at [_article/ko/how-to-contribute.md](https://github.com/github/opensource.guide/blob/main/_articles/ko/how-to-contribute.md#%EA%B8%B0%EC%97%AC%ED%95%A0-%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8-%EC%B0%BE%EA%B8%B0) is awkward.
so I translate the sentences 
Before
> 이전에 오픈소스에 기여한 적이 없다면, 케네디 미국 전 대통령으로부터 조언을 구하세요. _"Ask not what your country can do for you - ask what you can do for your country."_
After
> 이전에 오픈 소스에 기여한 적이 없다면, 미국 존 케네디 대통령의 명언을 떠올려보세요. 
_"Ask not what your country can do for you - ask what you can do for your country."_
_"국가가 나를 위해 무엇을 해줄 것을 바라기에 앞서, 내가 국가를 위해 무엇을 할 것인가를 생각해야 한다."_
=> [korean translation] translate sentences more naturally and translate wise saying 

_layouts/default.html
This PR adds cookie-less analytics to the opensource.guide website.
=> Add Fathom Analytics 📊

_articles/zh-hans/best-practices.md
Fix typo: `IOS` => `iOS`
-----
=> chore: fix typo

.github/dependabot.yml
=> Enable Ruby dependabot updates

.github/workflows/jekyll.yml
-----
Let's attempt to deploy using the GitHub Pages internal Jekyll build config with the custom Actions workflow.
=> Deploy using the GitHub Pages internal Jekyll build config

_articles/zh-hant/how-to-contribute.md
=> Remove https://yourfirstpr.github.io/ which is no longer available

_articles/zh-hant/how-to-contribute.md
-----
Deleted no longer existing `yourfirstpr.github.io` page in ZH-hans translation
Currently the domain does not exist, it has a 404 code which causes test spoilage.
=> Delete non-existent link in ZH-hant

CODEOWNERS
-----
Add legal-oss team as codeowners to the articles they want to reviews changes for.
=> Add legal-oss team as codeowners

_articles/zh-hant/maintaining-balance-for-open-source-maintainers.md
=> feat: translate maintaining-balance-for-open-source-maintainers.md

_data/locales/de.yml
-----
Add translation for friends tag.
=> Update German translation in footer

_articles/zh-hans/maintaining-balance-for-open-source-maintainers.md
add Chinese translation for maintaining-balance-for-open-source-maintainers
-----
=> docs: add zh-hans translation for maintaining-balance-for-open-source-maintainers

_articles/es/leadership-and-governance.md
The quote was just providing context in square brackets, but it had
gotten turned into a link in this translation. The destination didn't
exist, so tests were failing.
-----
=> Fix broken link on spanish leadership-and-governance

_articles/how-to-contribute.md
=> Fix capitalization of John F. Kennedy

_articles/starting-a-project.md
-----
This pr fixes a link that wasn't working
=> fix(starting-a-project) : unknown link

_articles/zh-hans/building-community.md
=> [zh-hans]Optimize sentences and keep them smooth

_articles/starting-a-project.md
-----
Changed outdated URL from this project: https://github.com/LogIN-/ospnc to https://github.com/toddcooke/namechecker.
=> Changed outdated URL

_articles/fr/metrics.md
-----
Fixed some typos, corrected grammar mistakes, and improved sentence fluidity in various parts of the document.
=> French/metrics.md: typo corrections, small reorganizations

_articles/es/starting-a-project.md
Corrected typographic errors: exclamation marks (¡), accented words, misplaced commas. The changes make the document more presentable. No changes were made to the translation.
-----
=> Corrected typographic errors

_data/locales/fa.yml
-----
I updated the Farsi translation and made it better.
=> Updated the Farsi translation

_articles/tr/best-practices.md, _articles/tr/maintaining-balance-for-open-source-maintainers.md
=> Fix turkish translations

_data/locales/it.yml
In this PR I've simply correct a typo in Italian translation.
-----
=> Fix italian translation

_articles/it/how-to-contribute.md
=> correct translation errors

.github/workflows/jekyll-preview.yml
=> fix: prefix a checkout action usage semver with 'v'

_articles/fa/maintaining-balance-for-open-source-maintainers.md
I translated maintaining-balance-for-open-source-maintainers.md into Persian so my people could use it.
=> translate to persian

_articles/de/getting-paid.md
Changed "relvante" to the correct spelling "relevante"
-----
=> Fix Typo in German Document

_articles/best-practices.md, _articles/bn/how-to-contribute.md, _articles/how-to-contribute.md, _articles/pcm/how-to-contribute.md, _articles/pcm/starting-a-project.md, _articles/starting-a-project.md
=> fix: Corrected typos and rephrased sentences

_articles/ko/maintaining-balance-for-open-source-maintainers.md
Since the document *Maintaining Balance for Open Source Maintainers* was not available in Korean, I have translated it.
-----
=> Translate 'Maintaining Balance for Open Source Maintainers' into Korean

_articles/de/starting-a-project.md
https://fairlanguage.com/service/ 403s.  Removing
-----
=> fix: remove link that is 403ing

Gemfile, Gemfile.lock
=> fix: update nokogiri due to security

_articles/how-to-contribute.md
-----
This PR fixes capitalization of "GitLab".
=> fix: typo in GitLab
