github/opensource.guide

CONTRIBUTING.md

The style guide link was uppercase which caused a 404 error.

Fixed typo in the link to the style guide

---

_includes/footer.html

This PR does two things:
1. Drop the `www.` just `github.com` (in my best JT voice).
2. Use HTTPS, not HTTP 
🤘

Correct footer URL to github.com

---

README.md
notices.md

This commit changes the 'but does not grant you any trademark permissions' to a parenthetical comment (an 'aside'), instead of having be part of the main sentence. With it part of the sentence, the reader may believe that 'so long as you note the license and give credit' applies to the trademark-related phrase, when in fact it relates the prior sections of the sentence.
This same sentence structure appears elsewhere in the guides so if this change is accepted the other locations will need be updated as well. I'm happy to do that and update the PR if desired.

Clarify the interaction of the CC-BY license and trademark rights

---

_layouts/default.html

The bug occurs because of the anchor's absolute positioning and its parent's `text-align: center` CSS property. All we need is just to wrap anchor and heading text into any HTML tag.
Closes #240

Fix misplaced anchors

---

_includes/footer.html

I just added autocomplete attribute to improve user experience. It helps user input their address very easy. Demo is below:
1. Find your IP address `preferences > Network`
2. run server `bundle exec jekyll serve --watch --incremental --baseurl '' --host <Your IP>`
3. Open the link in your mobile browser.
- iOS 
What do you think ?

 Improve email input user experience

---

_includes/footer.html
assets/css/custom.scss

I fixed #249. I change the class name and set css rule. I would like to extend `.border-right` in this code. Is there any way ?

Fix border-remains-when-vertically-aligned

---

assets/css/covers.scss

Fix margins so that cov-image does not touch ToC button

---

script/bootstrap

After #212, `script/bootstrap` needs to run `bundle update` to grab the latest version of dependencies.

Bundle update if check fails

---

index.html

#256 caused there to be nested `<p>` tags, causing the one with classes (`<p class="mb-0 text-gray">`) to be closed and a new paragraph to be opened without those styles applied.
Before:
After:

Fix nested <p> tags

---

CONTRIBUTING.md

Fixed the link. It now points correctly to the Jekyll main site.
404 page 
before

Broken link in environment setup section

---

_articles/code-of-conduct.md

The Rust CoC defers to the Citizen Code of Conduct to define what harassment is. This deferment is without revision history. Instead the Citizen Code of Conduct should be presented as example CoC instead as it is self contained and can be referenced by revision to ensure that future changes are not snuck into many projects CoC.

Swap out Rust CoC suggestion with Citizen CoC

---

.travis.yml

It looks like Travis does not trigger builds for the `gh-pages` branch by default. This adds the config [recommended here](https://docs.travis-ci.com/user/customizing-the-build#Safelisting-or-blocklisting-branches) to make it work.

Fix travis on gh-pages branch

---

docs/styleguide.md

This adds a missing word to a sentence in the styleguide docs.

Docs: fix a small typo in the styleguide

---

_includes/footer.html
_includes/head.html
_includes/search-result.html
_layouts/default.html
index.html
js/search.js
js/search_worker.js

When you fork this repo and push a commit to the `gh-pages` branch, it will get rendered on `yourname.github.io/open-source-guide`. This fixes it so the page renders properly on forks.
I'd like to update the PR guidelines to ask people to include a link to their changes so we can preview them without having to build the site locally.

Fix rendering on forks

---

assets/css/custom.scss

This removes italics and lightens the text in block quotes.
cc @sophshep - do you have any strong feels about this?
cc @wooorm @hzoo
Fixes #308 
…
…

Remove italics on blockquotes

---

CONTRIBUTING.md

Add a note to the contributing document to note some things to consider when adding links in a PR.

CONTRIBUTING: note linking policy.

---

script/bootstrap

See: https://github.com/github/scripts-to-rule-them-all/blob/1eaa4de/script/bootstrap#L30-L32
I was getting an error message when running `script/bootstrap` that said that `--binstubs` and `--path` weren't recognized parameters. That's true for `bundle update` but not `bundle install`, so I double-checked against the Scripts To Rule Them All repo, made the change and things worked for me.

Change bundle update to bundle install

---

README.md

Remove duplicated details in README.md and link to notices.md
Stab at suggestion from @bkeepers

Make notices.md canonical location of license info

---

docs/roadmap.md

Since https://github.com/open-source has been released, I changed the language discussing the move to it from https://opensource.guide.

Update roadmap.md's mention of github.com/open-source

---

Gemfile
_config.yml
_includes/footer.html
_layouts/article.html

When you push changes to the `gh-pages` branch on a fork:
>  Your site is having problems building: The tag `octicon` on line 29 in `/_layouts/article.html` is not a recognized Liquid tag. For more information, see https://help.github.com/articles/page-build-failed-unknown-tag-error/.
This plugin appears to only be whitelisted for GitHub staff, so this just replaces it with the `svg`s that it generates.
FYI: @parkr @benbalter not sure if there has been discussion about whitelisting this for everyone.

Remove jekyll-octicons plugin

---

_articles/how-to-contribute.md

Per #269, @aurynn suggested removing the "code"/"non-code" distinction. I've removed those terms here.

Remove "non-code" references

---

_articles/how-to-contribute.md

Per https://github.com/github/open-source-guide/issues/267, adding another example of where open source projects have asked for UX design help, thanks to @natdudley's suggestion.

Add Drupal example to design section

---

_includes/footer.html

@theo-armour asked in #350:
>>The link works on the website https://opensource.guide/notices/
>
> Interesting. I've never seen this page.
>
> How do you get to it from https://opensource.guide/ ?
This adds a link in the footer.  I don't know who started the trend, but I like how @benbalter uses "fine print" on http://ben.balter.com/ to link to legal content.
---

Add link to notices in footer

---

_config.yml
_includes/footer.html
_includes/head.html
_layouts/landing.html
js/locale.js

This updates #288 with support for switching between available translations.
Notable changes:
- List available translations in the footer of the site
- Auto-redirect to locale preferred by your browser settings if a translation is available
- Sets a cookie to remember the preferred locale and redirect to url for that locale
FYI @webknjaz @lijiangsheng1 @nandomoreirame

Locale switching

---

CONTRIBUTING.md
README.md
_config.yml
_includes/footer.html
_layouts/article-alt.html
_layouts/article.html
index.html
notices.md
script/html-proofer

@theo-armour brought up in #355:
> Open Source Guide(s) - singular or plural?
Fair question. It should always be "Open Source Guides", because there are multiple of them, and they live at opensource.guide (we can't make the TLD plural).
Thoughts?
Fixes #355

Fix page title

---

_articles/getting-paid.md

Prompted by @isaacs's suggestion: https://github.com/github/opensource.guide/issues/357#issuecomment-284636484
I started by adding a bullet about venture capital, but then I ended up reworking the whole section. :grin: I picked three common options for supporting projects themselves (vs. contributing on salaried time, which is the section above).
In the end, VC is a small mention, but I have strong feels on keeping it only in the context of creating revenue, vs. a means to an end.

Rework project funding section

---

_articles/starting-a-project.md

The link to a resource for checking for project name conflicts is broken, which is a shame. We'll just have to do without it.
Closes #374.

Remove link returning a 401

---

_articles/best-practices.md

We just published a [GitHub showcase of tools](https://github.com/showcases/tools-for-open-source) for open source projects. As it aggregates a bunch of existing community tools, I think it's a more appropriate link for the "Automate" section than the Integrations directory.

Link to GH Showcase with project tools

---

_articles/how-to-contribute.md

In chapter: how-to-contribute, there is a little checkbox label not matching.😇

Change <label> "for" attribute to match the right checkbox

---

.github/stale.yml

probot-stale automatically marks issues and PRs that sit open for long periods with no activity as stale, comments telling people and then closes them if there's no more activity. This saves a human having to manually curate this repository on a regular basis as things that aren't getting done will get closed.
Anyone (particularly @github/open-source-team and @github/open-source) please chime in here for thoughts on this and the specific values it's using.

Add probot-stale

---

docs/translations.md
script/sync-translation

@webknjaz [commented in #288](https://github.com/github/open-source-guide/issues/288#issuecomment-283927635):
> there's additional concern, which bothers me for a while: fixes or improvements to original articles go to this repo and there's no way to automatically confirm that translated version still corresponds original one.
I met with @alebourne and @zeke last week to talk more about how they plan to handle localization for several other GitHub projects. Long term, the plan is to adopt a translation management tool similar to what was [discussed in #295](https://github.com/github/open-source-guide/pull/295#issuecomment-281414390), which keeps track of which files need updated as content changes. They are well into the process of evaluating options and I'm following their progress …

I18n: Keeping translations updated

---

_includes/footer.html

This helps us ensure that the emails to this list are targeted and appropriate.

footer: add MailChimp group.

---

_articles/how-to-contribute.md
assets/js/index.js
index.html

- Add Open Source Friday to the "How To Contribute" list and tweak the wording to suggest that it's more than just discovery (this applies to other projects in that list too)
- On Fridays show a link to Open Source Friday on the index page

Point to Open Source Friday

---

_layouts/article.html

This is in the footer of all guides to people can jump quickly back to read more guides.
First part of https://github.com/github/opensource.guide/issues/427.

Add "back to all guides" link.

---

_articles/best-practices.md
_articles/building-community.md
_articles/code-of-conduct.md
_articles/finding-users.md
_articles/getting-paid.md
_articles/how-to-contribute.md
_articles/leadership-and-governance.md
_articles/legal.md
_articles/metrics.md
_articles/starting-a-project.md
_data/fields.yml
_layouts/article.html

Allow specifying `related` in article metadata and using that to add related guides to the bottom of an article.
Added an example to Best Practices which are bad and wrong and should be updated by @nayafia.
Currently looks like:
Fixes #427.

Add related guides to page footer.

---

_articles/en-US/best-practices.md

We've heard from people that they'd like examples of how to write an issue or PR template, and I love @TalAter's [Choose Your Own Adventure-style guide](https://www.talater.com/open-source-templates/#/). Thought it'd be a good example to add to this guide about best practices.

Add TalAter's choose your own adventure guide

---

README.md

Calling out in the README for new contributors that the site is powered by Jekyll, based on feedback. It's already mentioned in the contributing guidelines.

Clarify Jekyll in README

---

_articles/en-US/best-practices.md
_articles/en-US/how-to-contribute.md
_articles/en-US/leadership-and-governance.md
_articles/en-US/starting-a-project.md
docs/content-model.md

-----
I was reading the guides using my screen reader and was perplexed when I heard 'ex-community'. After inspecting the letters I found the usage of a non-standard abbreviation for example with `ex`.
I personally feel writing out `for example` is a lot clearer than `ex.`.
Thanks so much, love the guides!

Replace `ex.` in guides with `for example`

---

_articles/en-US/how-to-contribute.md

This pull request is submitted as response to @nayafia's comment to #477
Added first contributions under the "Opening a pull request section"
Highlighted that MaPR is a video tutorial and first contributions is a walkthrough and repository you can practice on.
-----

Add resource to practice submitting pull request

---

_articles/en-US/best-practices.md
docs/styleguide.md

Looks like these were moved from `script/test-prose` to [test/prose](https://github.com/github/opensource.guide/blob/gh-pages/test/prose) in 874a0496fdce252985dddffa2bf1b30e5640f46c (see [diff](https://github.com/github/opensource.guide/commit/874a0496fdce252985dddffa2bf1b30e5640f46c#diff-0e2bc0f03fe54e5e0fff129205e6ee92L8)).

Fix broken link to automated tests

---

_includes/footer.html

The {{ site.branch }} returns an empty string which generates a broken link.
I replaced it directly with "master" like it's generated in the in [nav.html](https://github.com/github/opensource.guide/blob/503dbe10704482b0529bc3cf568f81e3206910c0/_includes/nav.html#L12).

Broken link

---

script/bootstrap

- Use Bash for nicer syntax below (`&>`)
- Don't need to set `CC` to `gcc`
- Ensure we're in the right path

bootstrap: some cleanup tweaks.

---

_articles/es/legal.md
_articles/id/legal.md
_articles/ko/legal.md
_articles/legal.md
_articles/zh-cn/legal.md

Sometime between
https://web.archive.org/web/20171110143631/https://libraries.io/npm and
https://web.archive.org/web/20180617205253/https://libraries.io/npm
(now) that page stopped showng top licenses. Switching to equivalent
page that still does.
-----

update libraries.io url showing mit popularity for npm

---

_articles/code-of-conduct.md
_articles/es/code-of-conduct.md
_articles/es/starting-a-project.md
_articles/fr/code-of-conduct.md
_articles/fr/starting-a-project.md
_articles/id/code-of-conduct.md
_articles/ko/code-of-conduct.md
_articles/ko/starting-a-project.md
_articles/starting-a-project.md
_articles/zh-cn/code-of-conduct.md
_articles/zh-cn/starting-a-project.md

-----
Hi! Shouldn't every `##` heading except the last one appear under `toc:`? That is true in all other `_articles/*.md`, except in `code-of-conduct`. This PR adds the 2nd last section to the ToC.

Add missing ToC entry in code-of-conduct

---

assets/css/custom.scss

-----
Hey there!
First of all: thanks for this great project!
I noticed the e-mail input does not look great for users with a dark OS theme enabled (I'm one of these). This seems to be a very common issue in web design, as many users of macOS and Windows are not even aware there's a possibility of changing the appearance of OS native widgets; at least on most Linux distributions this is possible (GTK Themes). I even [ranted on Twitter](https://twitter.com/linusgroh/status/979349672602095617) about this once, sadly no great impact...
Long story short: one should NOT expect that the background color of an input will be `#ffffff` or similar! On the other hand, …

Fix form input for users with dark OS theme

---

_includes/nav.html

-----
Current `nav.html` only goes to `/` (without lang) even in non-English article pages. (like <https://opensource.guide/ko/starting-a-project/>)
This patch appends `page.lang` path in ‘Back to the index’ link to keep users inside translated pages.

Fix back to the index page link for non-English languages

---

assets/css/custom.scss

-----
This patch prevents breaking within Korean words, especially for heading text. This improves readability for Korean and has almost no impact on other languages. Or could you provide a way to add styles for specific languages?
Before:
After:
XRef: https://stackoverflow.com/questions/26044322/dealing-with-korean-text-breaking-words

Better word-break style for Korean

---

script/html-proofer

As noted at https://github.com/github/opensource.guide/pull/763#issuecomment-439726875
> I think the dupal.org site must be doing some kind of throttling, but I can't tell what -- the site works for me from a web browser or wget, but not curl or tests, and changing the user agent doesn't help. So ignoring for now.
This PR has the test do the ignoring, rather than me ignoring the test's failure report.

ignore drupal.org url that obtains 403 in tests but works

---

assets/css/custom.scss

-----
I introduced `word-break: keep-all` for better readability for Korean pages by #714. But this causes #789. By applying this patch, `word-break: keep-all` will affect only Korean pages.
XRef: https://www.w3schools.com/cssref/sel_lang.asp
Korean page:
Chinese page:

Move `word-break: keep-all` within Korean selector

---

.github/PULL_REQUEST_TEMPLATE.md

This is a new required check and needs to be done to each PR for the checks to pass.

Add PR requirement to enable GitHub pages 

---

assets/js/locale.js

-----
By previews code, when I were at https://opensource.guide/zh-cn/how-to-contribute/ or any other language page except English, if I want to switch to traditional Chinese language, after I click the bottom on the top right corner of the page,  https://opensource.guide/how-to-contribute/zh-tw/  is open instead of https://opensource.guide/zh-tw/how-to-contribute/. The former is wrong but the new one is right.
I fixed this bug.

Debug language switch navigation link-error

---

docs/styleguide.md
docs/translations.md

Adding missing emojis in styleguide.md and correcting the typo in translations.md
-----

Adding missing emojis and correcting typo

---

docs/translations.md

1. As per issue #1175 toc fields are not present in index.html but rather in articles. I have changed the points accordingly.
- [✓] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/master/CONTRIBUTING.md)?
- [✓] Have you explained what your changes do, and why they add value to the Guides?
-----

Updated point 4 and 5 in translations.md (Issue #1175)

---

_articles/pt/how-to-contribute.md

Fixing some typos in portuguese translation of how-to-contribute page.
-----

Some typo fixes in pt translation of how-to-contribute page

---

_layouts/index.html

-----
There were not any translations in h1 header tag with class="h00-mktg". (Only "Open Source Guides")
I used page.title (if exists) variable in order to apply translations into header section.

Applying translations into header (class=h00-mktg)

---

_includes/head.html

Adds the following `meta` tag for Google Search Console verification:
```html
<meta name="google-site-verification" content="c1kuD-K2HIVF635lypcsWPoD4kilo5-jA_wBFyT4uMY" />
```
/cc @SEOGoddess

Add google-site-verification meta tag

---

_includes/footer.html

Currently the link is broken because of the branch `master` renamed to `main`.
-----

Update branch name

---

_layouts/default.html

URLS without a protocol are an anti-pattern. This is safer and faster.
-----

Always load mc-validate.js over HTTPS

---

.github/dependabot.yml

Dependabot has the ability to keep GitHub Actions used in `.github/workflows` up to date.
See https://docs.github.com/en/github/administering-a-repository/keeping-your-actions-up-to-date-with-dependabot#example-dependabotyml-file-for-github-actions
-----

Add GitHub Actions to Dependabot config

---

_articles/de/getting-paid.md
_articles/es/getting-paid.md
_articles/fr/getting-paid.md
_articles/getting-paid.md
_articles/hu/getting-paid.md
_articles/id/getting-paid.md
_articles/ja/getting-paid.md
_articles/ko/getting-paid.md
_articles/ms/getting-paid.md
_articles/nl/getting-paid.md
_articles/pl/getting-paid.md
_articles/pt/getting-paid.md
_articles/ro/getting-paid.md
_articles/ta/getting-paid.md
_articles/tr/getting-paid.md
_articles/zh-hans/getting-paid.md
_articles/zh-hant/getting-paid.md

I've taken the same approach as Homebrew uses for our translations here and added the English, non-translated string to the various articles so readers can submit pull requests to update these translations.
Fixes #1928

getting-paid: add GitHub Sponsors reference

---

script/html-proofer

These are causing CI failures: https://github.com/github/opensource.guide/pull/2424/checks?check_run_id=2712132660#step:7:37

script/html-proofer: ignore more URLs.

---

script/html-proofer

These are failing in HTML Proofer but working in Safari.

script/html-proofer: ignore more Kickstarter URLs.

---

_config.yml

Removes [public-facing `package-lock.json`](https://opensource.guide/package-lock.json) addressing https://github.com/github/security/issues/4204.
File can always be seen in this repo of course 😉

Exclude package-lock.json

---

.github/workflows/stale.yml

Follow up to https://github.com/github/opensource.guide/pull/2534, I realize we wanted the action to mark **pull requests** as stale, not **issues** (which aren't supported in this repo)

Fix stale action by replacing issue with pull request

---

_articles/de/how-to-contribute.md
_articles/how-to-contribute.md
_articles/zh-hant/how-to-contribute.md

It seems to be a good idea to change mention "master" with "main". I also updated German and Chinese versions (I am not familiar with other languages, so I did not touch them).
-----

Replace master branch mentions with main

---

CONTRIBUTING.md

-----
The following Pull request, fix some grammatical issues and add punctuation to improve the readability of the `CONTRIBUTING.md` file.

fix grammatical and punctuation errors on CONTRIBUTING.md file

---

Gemfile

-----
html-proofer has had a few 4.x releases that are [breaking CI builds](https://github.com/github/opensource.guide/runs/7510507292?check_suite_focus=true). I tried a trivial configuration fix but got thousands of failures, which are probably spurious? Let's lock the html-proofer version for now.

Lock html-proofer version

---

.github/workflows/tests.yml
script/bootstrap

We don't need to bundle install twice, so skip it for actions

Make tests faster

---

_articles/metrics.md

-----
This pull request adds a link to the github blog to inform readers how to accomplish what the article is talking about (measuring/tracking maintainer responsiveness).

Add link to github action for measuring maintainer response time

---

_articles/best-practices.md
_articles/fr/best-practices.md
_articles/fr/building-community.md
_articles/fr/code-of-conduct.md
_articles/fr/finding-users.md
_articles/fr/getting-paid.md
_articles/fr/how-to-contribute.md
_articles/fr/legal.md
_articles/fr/starting-a-project.md

Fix: French typos

---

_articles/pt/maintaining-balance-for-open-source-maintainers.md

-----
In this PR I am proposing a translated version for the aforementioned article in Brazilian Portuguese. If there are any changes needed please let me  know.

Add pt-br translation to "Maintaining Balance for Open Source Maintainers"

---

CONTRIBUTING.md
script/html-proofer

The current build is failing for html proofer on the reddit links. At first I thought this was due to https, but realized this was likely being blocked after subsequent automated requests from the same ip.
-----

Add exclusion for reddit and updating contribution markdown.

---

_articles/how-to-contribute.md

Inconsistency - missing space:
Added the required missing space

Fixed editorial inconsistency

---

_articles/pcm/best-practices.md
_articles/pcm/leadership-and-governance.md

Prior to this change the tests would fail with:
Checking 358 external links...
Ran on 300 files!
- _site/pcm/best-practices/index.html
*  linking to internal hash #share-ownership-of-your-project that does not exist (line 557)
<a href="../building-community/#share-ownership-of-your-project">share ownership of the project</a>
This fixes the internal anchor to match the translated header text.

Fix test failure caused by untranslated internal link

---

_data/locales/bg.yml

Fix a problem with the data structure in the bg.yml datafile
The top level key was still `en` from the english template file, causing the top nav/language chooser not to render correctly

Fix data structure problem in bg

---

.github/workflows/jekyll-preview.yml
.github/workflows/jekyll.yml
.github/workflows/stale.yml
.github/workflows/tests.yml

Adhere to best security practices and use SHAs for GitHub Actions and not tags (they can be changed).
I used [`frizbee`](https://github.com/stacklok/frizbee) to do this.
```shell
brew install stacklok/tap/frizbee
frizbee ghactions -d .github/workflows/
```
-----

fix: use SHAs for GitHub Actions instead of tags

---

.github/dependabot.yml

Group dependencies by minor/patch to reduce PRs. Keep major version updates in their own PRs for visibility and testing.
-----

chore: group dependencies

---

.github/workflows/stale.yml
.github/workflows/tests.yml

fix: code scanning alerts re: workflows permissions

---

_includes/head.html

The value `no-preference` was never implemented by any browser and has been removed from the specification.
See https://www.w3.org/TR/mediaqueries-5/#prefers-color-scheme and https://github.com/w3c/csswg-drafts/issues/3857#issuecomment-634779976
-----

Remove invalid media query

---

.github/workflows/jekyll-preview.yml

based on feedback from security folks
-----

fix: use deploy environment for build job and replace ref with sha to prevent TOCTOU

---

.gitignore
script/html-proofer

fix: link that is 403ing due to redirect

---

script/html-proofer

-----
Currently PRs are failing tests because rockwoodleadership.com URLs are 403ing.

chore: add rockwoodleadership urls to html_proofer ignores
